sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: wzj
  alioss:
    access-key-id: LTAI5t6zSP6hF8wadpfeJF4c
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-secret: dz1MgQ84RgLj2ZglUf3DSptcmPgrMY
    bucket-name: web-mike
  redis:
    port: 6379
    host: localhost
    password: wzj
    database: 0